FROM python:3.12-slim
WORKDIR /app
COPY . .
ENV PYTHONPATH=/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DRY_RUN=1
ENV GRC_LIVE_SCAN=0
ENV CISO_PUSH=0
ENV RISKREADY_PUSH=0
ENV OUT_DIR=/out
ENV IN_DIR=/in
ENV FIXTURES_DIR=/fixtures/demo
CMD ["python", "collectors/grc_loader.py"]
