[global]
  workgroup = LAB
  netbios name = LABSMB
  server signing = disabled
  server min protocol = NT1
  ntlm auth = yes
  map to guest = Bad User
  guest account = nobody
  disable netbios = yes
  smb ports = 445
[public]
  path = /srv/share
  guest ok = yes
  read only = yes
