# LAB ONLY: directory listing + deprecated TLS + anon ciphers + weak self-signed cert on purpose.
worker_processes 1;
events { worker_connections 64; }
http {
  access_log off;
  server { listen 80; root /srv/www; autoindex on; }
  server {
    listen 443 ssl;
    ssl_certificate /etc/nginx/tls/cert.pem;
    ssl_certificate_key /etc/nginx/tls/key.pem;
    ssl_dhparam /etc/nginx/tls/dhparam.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "aNULL:eNULL:ALL:@SECLEVEL=0";
    ssl_prefer_server_ciphers on;
    ssl_conf_command MinProtocol TLSv1;
    ssl_conf_command CipherString "ALL:@SECLEVEL=0";
    root /srv/www;
    autoindex on;
  }
}
